Fixed issue with fresh start up failing
no ref

When setting up the app from fresh via `yarn dev` (no previous docker images,
no built `dist` dir), it was possible for an issue to occur where the container
tries to load `app.ts` before it is built, resulting in the error:

```
activitypub-1  | yarn run v1.22.22
activitypub-1  | $ concurrently "yarn build --watch" "node --inspect=0.0.0.0:9229 --watch dist/app.js"
activitypub-1  | [1] Debugger listening on ws://0.0.0.0:9229/99b125ec-4ba2-4fe8-9c14-e94ffa86b922
activitypub-1  | [1] For help, see: https://nodejs.org/en/docs/inspector
activitypub-1  | [1] node:internal/modules/cjs/loader:1386
activitypub-1  | [1]   throw err;
activitypub-1  | [1]   ^
activitypub-1  | [1]
activitypub-1  | [1] Error: Cannot find module '/opt/activitypub/dist/app.js'
activitypub-1  | [1]     at Function._resolveFilename (node:internal/modules/cjs/loader:1383:15)
activitypub-1  | [1]     at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
activitypub-1  | [1]     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
activitypub-1  | [1]     at Function._load (node:internal/modules/cjs/loader:1192:37)
activitypub-1  | [1]     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
activitypub-1  | [1]     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
activitypub-1  | [1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
activitypub-1  | [1]     at node:internal/main/run_main_module:36:49 {
activitypub-1  | [1]   code: 'MODULE_NOT_FOUND',
activitypub-1  | [1]   requireStack: []
activitypub-1  | [1] }
activitypub-1  | [1]
activitypub-1  | [1] Node.js v22.22.0
activitypub-1  | [1] Failed running 'dist/app.js'. Waiting for file changes before restarting...
activitypub-1  | [1] node --inspect=0.0.0.0:9229 --watch dist/app.js exited with code 0
activitypub-1  | [0] $ esbuild src/app.ts --sourcemap --platform=neutral --bundle --packages=external --outfile=dist/app.js --watch
activitypub-1  | [0] [watch] build finished, watching for changes...
```

This changeset fixes the issue + also updates the debugger setup so that
sourcemaps are correctly loaded and debugging can be easily stared from vscode
flavoured IDE's